internet4000/radio4000

app/index.html

Our `<noscript>` fallback was hidden by the dummy-app fixed on top. Now the dummy app is initially hidden but immediately shown with JS (from index.html).
Closes https://github.com/internet4000/radio4000/issues/36

Fix dummy-app hiding the no-js fallback

---

app/app.js

This will allow the `radio4000-player` (and potentially other parts) to know the current database URL of Radio4000.
Depends on https://github.com/internet4000/radio4000-player/pull/63

Expose the current DB

---

app/channel/tracks/track/edit/controller.js
app/channel/tracks/track/edit/route.js
app/channel/tracks/track/edit/template.hbs
app/components/track-edit/component.js
app/components/track-edit/template.hbs

- rename `updateTrack` to `submitTask` so it is consistent with the other track-form components
- call preventDefault (not sure why it's needed)
- remove extra `notify` abstraction

Fix edit track in Firefox

---

app/styles/components/_playback-external.scss
package.json
yarn.lock

Upgrades the player. Since we don't yet use shadowdom our radio4000 styles from `.Btn` are conflicting with player styles. I added a quick fix but some day we should rethink this.

Upgrade radio4000-player

---

app/channel/followers/template.hbs
app/channel/index/template.hbs
app/components/channel-sharer-url/component.js

Add two inputs at the bottom of a channel.index page
- url
- embed (iframe)
At the bottom of , same on "followers", but here we can't login.
https://deploy-preview-106--radio4000.netlify.com/stephidisco3000
Condition some text to only appear to unexperienced users with `cuurentUser.channel.isexperienced`, also cannot be seen in the deploy since no loggin

add sharer links

---

app/channels/index/template.hbs
app/channels/search/controller.js
app/channels/search/template.hbs
app/components/app-root/component.js
app/components/btn-favorite/component.js
app/components/channel-card/template.hbs
app/components/feedback-form-google-spreadsheet/component.js
app/components/feedback-form-google-spreadsheet/template.hbs
app/components/play-btn/component.js
app/components/play-random-channel/component.js
app/components/play-random-channel/template.hbs
app/components/play-shuffle-btn/component.js
app/components/play-shuffle-btn/template.hbs
app/index.html
app/services/player.js
app/styles/base/_button.scss
app/styles/components/_channel-card.scss
app/styles/components/_loader.scss
package.json
tests/integration/components/play-random-channel/component-test.js
yarn.lock

The goal of this PR is to add an indicator to our play buttons while it's loading.
- play methods moved together in player:service as tasks
- `{{play-btn}}` is reused for `{{play-btn-shuffle}}` and `{{play-random-channel}}`
- because of that, they all have a `clickTask` available
- this `clickTask` abstracts away whichever task they actually call
- the class `is-running` is added to the buttons while the task is running/loading
**Questions**
How do we make it obvious that it is loading in each button? I tried some different things but it's not quite smooth yet.
It's a bit annoying that the focus outline-styles appear as you're tapping the button. It should only come on focus.
Anything else?
Preview: http://feature-play-buttons--radio4000.netlify.com/

Improve play buttons

---

app/components/channel-card/template.hbs
app/components/channel-header/template.hbs
app/helpers/link-hashtags.js
tests/integration/helpers/link-hashtags-test.js

Adds a `{{link-hashtags}}` that can be used to link hashtags to a track search.
So instead of
```
{{channel.body}}
```
you would do
```
{{link-hashtags channel.body channel.slug}}
```
It hardcodes the links as normal `<a>` but Ember seems to catch them anyway. For now I only added it to the channel-header component.

Add link-hashtags helper

---

app/components/bookmarklet-link/template.hbs

Just realized that Youtube changed their SEO strategy, affecting our bookmarklet.
We used to pass the track URL and the title, but they have added `- Youtube` to every of their title, affecting all our Bookmarklet users.
it is actually a quick fix, but a major pain, since every one having the old bookmarklet is getting annoyed.

remove bookmarklet from fetching title

---

app/styles/app.scss
app/styles/base/_normalize.scss
app/styles/layout/_layout.scss
package.json
yarn.lock

So, newer node-sass can't import .css files. So I decided to get rid of our external CSS dependencies: `suitcss-base` and `normalize.css`.
The only thing (really) needed from suitcss-base was the box-sizing. Added it manually.
Since the SCSS versions of normalize out there aren't up to date I copy/pasted it and renamed to .scss file. Not ideal, but works.

Fix style deprecations

---

app/channels/map/controller.js
app/channels/map/template.hbs
tests/acceptance/map-test.js

Adds a little test that the /map route actually renders.
It wouldn't have caught this bug https://github.com/internet4000/radio4000/issues/235 because the broken link-to was only rendered for authenticated users (which isn't part of our current tests). Still, better than nothing…

Test that the map route renders

---

app/components/track-contextual/template.hbs
app/components/track-edit/component.js
app/components/track-edit/template.hbs
app/components/track-form/component.js
app/components/track-item/component.js
app/components/track-item/template.hbs
app/components/x-playback/component.js
app/components/x-playback/template.hbs
app/models/track.js
app/services/player.js
app/styles/components/_track.scss
app/utils/youtube-api.js
package.json
yarn.lock

Related PRs:
- https://github.com/internet4000/radio4000-player/pull/110
- merged https://github.com/internet4000/radio4000-api/pull/46
In this PR:
It's nice as it opens a nice patern for adding more providers such as Discogs or Bancamp links.
Maybe some feature above are for a v2. We have to take care that it does not become annoying.
- add a `/settings/channel/tools` root with the possibility to hide the track edit suggestions
- add a `/tools` route with a `massTagEditor` and `massTrackEdit` and `massTrackUrlFix`

feat: add notification on track when its media is not available

---

app/models/track.js

When you edit a broken (not available) track URL to a working one it was not using the new YouTube ID to check for track availability.

Fix old YouTube ID for availability check

---

app/app.js
app/components/account-provider-link/component.js
app/components/channel-header/component.js
app/components/x-playback/component.js
app/helpers/time-ago.js
app/index.html
app/models/track.js
app/services/ui-states.js
app/settings/account/controller.js
app/utils/youtube-url-to-id.js
app/validators/youtube-url.js
package.json
yarn.lock

Start using https://github.com/ef4/ember-auto-import
instead of the traditional `import {someThing} from npm:some-thing`

use ember-auto-import

---

app/components/track-contextual/template.hbs
app/styles/components/_list.scss
app/styles/components/_track.scss
app/styles/utilities/_displays.scss

This PR improves the keyboard accessibility of our track lists.
Before (https://radio4000.com/nomads)
1st tab: focus track
2nd tab: focus button (but can't open the select)
3rd tab: focus invisible select (but can't see that you focus it)
After (https://deploy-preview-255--radio4000.netlify.com/nomads)
1st tab: focus track
2nd tab: focus select (with fancy css so the button looks focused)
.. and a bit more visible focus styles.
I really wanted the contextual menu to open with `enter` press as well, but apparently that is not how the web works. You use `space`. People won't understand buuut that's how it is. Unless someone has an idea?

Improve focus styles on tracks

---

app/styles/base/_base.scss
app/styles/components/_manchet.scss
app/styles/components/_tabs.scss

This PR only switches the decoration of the channel title, on a channel homepage, and its subpages.
Before, when the `channel.index` was active, the h1 title was underline, now it is not.
Before, when the `channel.sub-page` was active, the h1 title, was not underlined, now it is, because it means that the title can be clicked like a link to go back to the homepage.
This is very minor but I think it explains better how the channel page works, and it frees the homepage from an unecessary horizontal line, giving emphasis of the title's typography.

feat: change channel h1 to be underlined when it should be clicked (aka, outside of channel.index)

---

app/components/aside-channels/component.js
app/components/aside-channels/template.hbs
app/components/channel-cover/component.js
app/components/channel-cover/template.hbs
app/components/is-loading/component.js
app/components/is-loading/template.hbs
app/components/sort-indicator/component.js
app/components/sort-indicator/template.hbs
config/optional-features.json
package.json
yarn.lock

After seeing https://mobile.twitter.com/gavinjoyce/status/1056592816082706432 I wanted to try and enable template-only components where possible for performance. Especially the channel-cover component, which is used a lot.
It's important to remember that template-only components require "named arguments", which was releleased in Ember 3.1. That means prefixing with arguments in templates with ampersand, so `{{@title}}` instead of `{{title}}`.
More on the feature:
- https://github.com/emberjs/rfcs/blob/master/text/0278-template-only-components.md
- https://www.emberjs.com/blog/2018/04/13/ember-3-1-released.html#toc_introducing-optional-features-3-of-4

Use template only components

---

app/components/focus-input/component.js
app/components/modal-dialog/component.js
app/components/track-form-add/template.hbs
app/components/track-form/component.js
package.json
yarn.lock

So, the modals were not closing on 'Escape' when our {{focus-input}} were focused inside dialog windows.
This happened because ember-keyboard blocks keyboard events inside (ember) textareas and text inputs by default.
Fix was to add `this.set('keyboard.isPropagationEnabled', true)` on the focus-input to allow it to bubble keyboard events. Found it in ember-keyboard docs.
Closes #269

Fix escape shortcut on dialog windows

---

app/components/focus-input/component.js
config/environment.js

This a little bit annoying but my last "fix" accidently enabled ALL keyboard events to trigger inside inputs. What we want is only "Escape" to trigger. Hopefully there is a cleaner way to do this but I don't see it at the moment.

Fix keyboard events on inputs

---

app/components/track-contextual/component.js
app/components/track-contextual/template.hbs
app/components/track-item/component.js
app/styles/components/_track.scss

This PR just shows when a Discogs release link is available on a track, in every radio track list.
It is a mvp and can be improved in a certain future.
Some hints:
- maybe we need to show a track detail page/overlay on which you can open the links instead of having to copy them (more natural)
- maybe on this same overlay we can make some api calls to Discogs and display some more data regarding the track (expensive api calls)

mvp for showing discogs when available on a track

---

app/mixins/keyboard-shortcuts-global.js

When the user is on a channel route, `P` will play its first track.
Thought it would be nice to have the same behavior has Play, then play random, but also the user can do that with keyboard shortcuts for the player already. So maybe some other time if the need is there.

add P for play current channel keyboard shortcut

---

app/about/contact/template.hbs

just a more accurate contact page

add some updates to contact page

---

tests/acceptance/autocomplete-test.js

Currently tests are failing because the autocomplete test attempts to visit Radio Oskar, where the favorites are broken in the database. So I changed the test to no longer visit it... Of course still need to fix the db but at least everything won't fail because of it.

Fix autocomplete test

---

app/styles/components/_track.scss

this should fix the contextual menu select on track being too wide compare to the size of its parent container.

fix contextual menu being too wide

---

app/channels/explore/template.hbs

The inline search on /explore works by filtering the DOM through the "Jets" plugin.
Our problem was that we filter elements inside the selector `.Grid`, which is also used in the menu overlay. So when the menu is empty after searching, it was because Jets is also filtering that………
Fixed by using a unique class name instead.
Fixes #342

Fix /explore search+menu bug

---

app/styles/components/_channel-card.scss
app/styles/components/_channel.scss

visual improvement? I think it is nicer to look at

make channel's body links (tags) bold instead of underline

---

app/components/aside-channels/template.hbs

moved map before explore on /channels aside navigation.
- map loads, faster, so our user should see a fast loading page after explore (if they follow the logic pattern of clicking item number two)
- I guess people looking for /explore don't really mind the extra 50px to click the btn
- there are still the quick search if you know where you want to go, and kbd shortcuts

map before explore

---

app/styles/base/_button.scss
app/styles/base/_form.scss

we set `box-sizing: border-box` on `html` and let all elements inherit it. but still, the inputs would have `content-box`. Don't know why. This seems to fix it.

Fix inputs wider than share box in webkit

---

app/channel/tracks/controller.js
app/channel/tracks/route.js
app/channel/tracks/template.hbs
app/channel/tracks/track/index/route.js
app/channel/tracks/track/index/template.hbs
app/channel/tracks/track/route.js
app/components/channel-header/template.hbs
app/components/tracks-list/component.js
app/components/tracks-list/template.hbs
app/templates/head.hbs

- add a /channel/:track route & template
- add the possibility to locate the currently playing track, in the cms

Add track route + locate track in cms

---

app/channel/home/template.hbs
app/channel/index/controller.js
app/channel/player/controller.js
app/channel/player/route.js
app/channel/player/template.hbs
app/components/app-root/component.js
app/components/x-playback/component.js
app/components/x-playback/template.hbs
app/router.js
app/services/ui-states.js
app/styles/app.scss
app/styles/components/_aside.scss
app/styles/components/_channel-screen.scss
app/styles/components/_input-autocomplete.scss
app/styles/components/_playback.scss
app/styles/layout/_root.scss
tests/unit/channel/player/controller-test.js
tests/unit/channel/player/route-test.js

- improve fullscreen mode by using the browser's fullscreen. It allows us to have on mobile and desktop a better experience since the browser's URL bar is hidden, and only the radio4000-player (Aside--right, to have the r4-cms layout controls) is displayed fullscreen.
- add a new mode, docked, at /channel/player.
It shows the channel cover image in fullscreen, a play button, then the player displayed in the DOM (static, docked). The UX should favor movements between modes.

Better fullscreen + dock player mode

---

app/channel/tags/route.js
app/channel/tags/template.hbs
app/channel/template.hbs
app/components/channel-tags/component.js
app/components/channel-tags/template.hbs
app/components/tracks-without-tag/component.js
app/components/tracks-without-tag/template.hbs
app/helpers/link-hashtags.js
app/models/channel.js
app/models/track.js
app/router.js
app/styles/components/_tags.scss
app/utils/hashtag.js
tests/integration/components/channel-tags/component-test.js
tests/integration/components/tracks-without-tag/component-test.js
tests/unit/channel/tags/route-test.js

List all tags and order them by popularity, most occurrences first.
- track model now have a computed property `track.tags`
- add a `/channel/tags` route
- list selected tags, those in the channel.body
- list tracks with no tags, so it is easier to start editing 
What we can think about in the future:
- show how many tracks are in a `tag`; ex: `house (200)`
- should the tags link display all tags on the tags page, or continue linking to `/:channel/tracks?search=#tag`
- where to list all tracks without discogs
- where to list all tracks with broken media links
- how to *mass edit* multiple tracks at once, add tags. remove tags, clean things up
- how to rename a tag; ex: rename `#PM` to `#pm`

add /:channel/tags

---

app/about/intro/route.js
app/about/intro/template.hbs

Right now on https://radio4000.com/about it is showing all radios.
Thinking this is simpler, but we're still extending ChannelsIndexRoute, where I override the model, so that is actually unneded.

basic latest featured

---

app/styles/base/_config.scss

We got a comment in the feedback form that the YouTube volume button isn't visible. 
I checked and the thing is that YouTube hides it below certain sizes. On my Firefox desktop, the volume button disappears below 1000px. BUT, if I change the "player sidebar" from 20 to 21rem, it stays all the way to mobile.

Show YouTube volume button longer

---

app/utils/youtube-api.js

fix for when youtube quotas are not working, we can't check track availability, therefore just allow

fix issue when youtube quota have been used

---

app/channels/template.hbs
app/styles/base/_button.scss
app/styles/components/_aside.scss
app/styles/components/_input-autocomplete.scss
app/styles/components/_playback.scss
app/styles/layout/_container.scss
app/styles/layout/_layout.scss
app/styles/layout/_root.scss
app/styles/layout/_sections.scss

- main search and main nav btn top the bottom left
- dock the player to the top sticky, when on mobile/tablet
The objective is to solve the issues with the player being over the interface on mobile.
Also I feel it could be nicer on mobile when browsing the page.
To me this is an experiment I'd like to try live, and see how this feels by real usage.

fix main-menu to bottom right, and dock player to the top on mobile

---

app/components/x-playback/template.hbs
package.json
yarn.lock

Use `#text2speech` in the `track.body` for the bowser `window.speechSynthesis`  to *say out loud* the track's description.
It uses the new `<radio4000-player speech="true">` capabilities
Easter egg?
default?
customization in cms?
let's find out!

add text to speech for #text2speech with new <r4-player speech=true>

---

app/components/auth-delete-account/template.hbs
app/components/channel-edit-details/component.js
app/components/channel-edit-details/template.hbs
app/components/map-position-selection/template.hbs
app/menu/controller.js
app/settings/channel/backup/template.hbs
app/settings/channel/delete/template.hbs
app/settings/channel/image/template.hbs
app/styles/base/_base.scss

try to fix this https://github.com/internet4000/radio4000/issues/141
not sure why it is not working.
Seems that the computed property ignores the updates on the `proxy` object.
Any idea why?

Try to disable the save channel settins btn if no change

---

app/auth/login/template.hbs
app/auth/signup/template.hbs
app/components/user-signup/template.hbs
app/styles/components/_aside.scss

improve a bit more the auth flow styles

improve login/signup styles
