testem.js

Copied from travis' official testem file.

Fix Chrome CI locally on OS X

---

app/components/play-pause-btn/component.js

The play button tooltip did not show the keybinding. This PR fixes the tooltip accordingly.
Cheers

Fix Play button tooltip

---

app/help/template.hbs

remove help section on login with social providers only

---

LICENSE

add licese GPLv3

---

app/channels/new/controller.js

fix new channels having their slug automaticaly suffix with a random string.
Now it only does it if the channel slug (the new channel wants) already exists.

WIP: fix/new-channel-slug-suffix only if required

---

app/styles/components/_playback.scss
app/styles/layout/_root.scss

- fix mini player
- put elements affect by root class togling in root.scss

fix mini player and move root styles in root

---

app/channel/delete/controller.js
app/channel/delete/route.js
app/channel/delete/template.hbs

refactor delete notification and template

---

app/channel/tracks/track/index/route.js
app/components/x-playback/component.js
app/components/x-playback/template.hbs
app/router.js
app/styles/components/_aside.scss
app/styles/components/_playback.scss
app/styles/layout/_root.scss
package.json
yarn.lock

Checkout `refactor-responsive` branch from https://github.com/internet4000/radio4000-player/pull/77 and then test it inside R4 in this branch.

Upgrade radio4000-player to get more responsive styles

---

app/channel/followers/template.hbs
app/channel/index/template.hbs
app/components/channel-sharer-url/component.js
app/components/channel-sharer-url/template.hbs
app/components/focus-input/component.js
app/components/track-add-inline/template.hbs
app/components/track-edit/template.hbs
app/components/track-form-add/template.hbs
app/components/user-login/template.hbs
app/components/user-signup/template.hbs
app/styles/components/_manchet.scss
tests/integration/components/track-form-add/component-test.js

two component APIs
- input to share `https://radio4000.com/radio-slug`
- if `iframe=true` input to share `<iframe src="http://api.radio4000.com/iframe?slug=radio-slug">`
- update its api to allow either `autoFocus` or `autoSelect` or a combinaison of both.
- update inputs accrros the app to match focus / select requirements

channel-sharer-url api + focus-input api

---

app/add/template.hbs
app/channel/delete/controller.js
app/channel/edit/controller.js
app/channel/index/controller.js
app/channel/index/route.js
app/channel/index/template.hbs
app/channel/template.hbs
app/channel/tracks/route.js
app/channel/tracks/template.hbs
app/channels/new/controller.js
app/components/app-root/template.hbs
app/components/track-item/template.hbs
app/components/user-signup/template.hbs
app/mixins/create-track.js
app/models/channel-public.js
app/models/channel.js
app/models/image.js
app/models/track.js
app/models/user.js
app/timestamp/transform.js
tests/unit/timestamp/transform-test.js

Edit: timestamps were broken after the last `feature/timestamps` branch. The `created` field on channels was incorrectly being updated to a new timestamp every single time something with the channel was changed. Same with tracks. Editing a track would set `created` to "now". This reverses it and fixes more stuff.

Fix timestamp

---

app/add/route.js
app/add/template.hbs
app/channel/tracks/track/edit/template.hbs
app/components/app-root/template.hbs
app/components/track-edit/template.hbs
app/components/track-form/component.js
app/components/track-item/template.hbs
app/styles/components/_modal-dialog.scss

use the right markup
also deam the background of the overlay for more focus

improve /add page layout and overlay

---

app/components/map-position-selection/template.hbs
app/components/map-world/template.hbs
app/styles/components/_map.scss

Attempt to improve the marker. Testing the location of `Baltic` shows how far off our current marker is.

Adjust map marker position

---

app/channel/index/route.js

fix scroll up on channel index

---

app/channels/map/template.hbs
app/styles/base/_button.scss

add "add my radio" button on /map

---

app/auth/route.js

Remove login route from history, after login success

---

app/components/channel-header/component.js
app/components/channel-header/template.hbs

Feature/hide channel.updated if > two month

---

app/components/feedback-form-google-spreadsheet/component.js
app/components/feedback-form-google-spreadsheet/template.hbs

let's see if that really really works
fixes #131

add basic spam protection

---

app/bookmarklet/template.hbs
app/components/aside-left-toggle/template.hbs
app/components/bookmarklet-link/template.hbs
app/styles/components/_aside.scss
tests/integration/components/aside-left-toggle/component-test.js

improve UX of bookarmarklet page

Bookmarklet route ux

---

app/components/x-playback/component.js
app/mixins/keyboard-shortcuts-global.js
app/services/ui-states.js

Fix shortcuts with multiple actions

---

app/channels/map/template.hbs
package-lock.json

Hide 'add my radio' on map when logged out

---

README.md

First go on clarifying how our auth works. I don't want to go to deep so I left all the links I could.
Does it make sense @lucho1112? What is left unanswered?
Closes #182

WIP Clarify docs on authentication

---

app/components/x-playback/template.hbs
app/services/player.js
app/styles/base/_form.scss

Requires new radio4000-player release with https://github.com/internet4000/radio4000-player/pull/96
Closes https://github.com/internet4000/radio4000/issues/180

Adapt to new player query architecture

---

app/index.html
ember-cli-build.js
package.json
yarn.lock

Testing if it's faster with just one css file. We already concat the scripts.

Concat styles and scripts

---

app/channels/index/controller.js
app/channels/index/route.js
app/channels/index/template.hbs
tests/unit/channels/index/controller-test.js

wish it did not reload the UI where the buttons are, but not sure how.

add reload selection button on `/`

---

app/about/intro/route.js
app/about/intro/template.hbs
app/channels/index/route.js

By reusing the model hook from our homepage.
Fixes #219

Make featured radios on /about random

---

app/channel/edit/template.hbs

Add link to create a backup of a radio

---

README.md

Just took the liberty to add more information about this project I think they lacked.
Also added more found on the matric chat https://riot.im/app/#/group/+radio4000:matrix.org.

Update readme with some more notes on the project

---

app/add/route.js

Don't merge (yet), testing things out.
Closes #222 
**Update**: LGTM.

Fix add?url=

---

app/channels/index/controller.js
app/channels/index/route.js
app/channels/index/template.hbs

Hide featured radios without image

---

app/channels/index/controller.js
app/channels/index/route.js
app/channels/index/template.hbs
app/mixins/validate-slug.js
app/settings/channel/index/controller.js
app/settings/channel/index/route.js
app/settings/channel/index/template.hbs
app/settings/channel/route.js
app/styles/components/_flash-messages.scss
app/utils/clean.js
package.json
yarn.lock

No more featured radios without images and fixed some bugs on the new settings page.

Release 5.9.1

---

app/channels/map/template.hbs

fixes https://github.com/internet4000/radio4000/issues/235

fix: link to add radio to map

---

app/channels/index/route.js
app/channels/search/controller.js
app/channels/search/route.js
app/channels/search/template.hbs
app/components/channel-card/component.js
app/components/channel-card/template.hbs
app/components/channel-cover/template.hbs
app/styles/components/_channel-card.scss
app/styles/components/_cover.scss
app/styles/layout/_grid.scss
package.json
yarn.lock

Since the https://github.com/internet4000/radio4000/pull/256 branch included lots of tests and became a bit messy, I started fresh. Still testing things to see which tweaks are worth it.

Faster homepage and faster /search (all channels) routes

---

app/components/track-item/component.js
app/components/track-item/template.hbs
tests/integration/components/track-item/component-test.js

Added a couple of small tests for {{track-item}}.

Add tests for track-item component

---

package.json
yarn.lock

See https://github.com/internet4000/radio4000-player/issues/130

Upgrade radio4000-player

---

app/channels/map/route.js
app/components/tracks-list/component.js

Let's see if this works as intended on the netlify deploy preview…
Fixes #271

Change query params for /map to not affect URL history

---

app/about/template.hbs
app/channel/delete/template.hbs
app/channel/loading/template.hbs
app/channel/template.hbs
app/components/aside-channels/template.hbs
app/components/aside-navigation/template.hbs
app/components/aside-settings/template.hbs
app/index.html
app/settings/template.hbs
app/styles/components/_tabs.scss

More mini-tweaks after merging layout-test. Changed indention back to tabs here and there.

Fix indention to tabs

---

app/styles/base/_button.scss
app/styles/base/_config.scss
app/styles/components/_map.scss
app/styles/layout/_root.scss

mini improvements on layout

---

app/components/aside-navigation/component.js
app/components/aside-navigation/template.hbs
app/components/navigation-toggle-btn/component.js
app/mixins/keyboard-shortcuts-global.js
app/services/ui-states.js

meh
why does it not focus the navigation (tab focus) when it is toggled?!?!?!

improve aria on navigation and fail to put tab focus

---

app/components/app-root/template.hbs
app/components/play-random-channel/component.js
app/mixins/keyboard-shortcuts-global.js
app/services/player.js

- Changed shortcut for going to homepage from <kbd>gh</kbd> to <kbd>gg</kbd>
- Removed shortcut <kbd>gf</kbd> to go to /feedback
- Changed shortcut for going to favorites from <kbd>gs</kbd> to <kbd>gf</kbd>
- New: both <kbd>gf</kbd> (favorites) and <kbd>gt</kbd> (tracks) are now contextual. That is, they will prioritize using the channel you are browsing, then your own channel.

Change shortcuts

---

public/_redirects

fix netlify subdomians for seo by redirected to our main domain

---

app/components/aside-navigation/template.hbs
app/styles/base/_colors.scss
app/styles/components/_aside.scss
app/styles/components/_channel-card.scss
app/styles/components/_contextual-toggle.scss
app/styles/components/_logo.scss
app/styles/components/_tabs.scss
app/styles/layout/_grid.scss
app/styles/layout/_root.scss

a little proposition on how we can start using the overlay space.
It uses `.Grid` and `nav` and `.Tabs`

use overlay space

---

app/index.html

Heard it made a 1sec difference when they did this on chrome.com - want to test and see if we're also that lucky!

WIP Replace preloaded fonts with preconnect for CDN

---

app/add/template.hbs

just visually center the add page

center add section

---

app/components/track-form-add/template.hbs

It is stupid to have let it all this time hidden.

add-current-track  button

---

.eslintrc.js
app/auth/login/controller.js
app/auth/login/route.js
app/auth/login/template.hbs
app/auth/route.js
app/components/user-login/component.js
tests/unit/auth/login/controller-test.js

Fix for #345 
Unfortunately we can't test on the deploy preview, as auth isn't allowed on those domains. But in my local tests, it does work now on iOS. Can't be 100% though…

Switch to redirect login for iOS

---

app/index.html

improve offline dummy and transition opacity

---

app/auth/signup/controller.js

fix signup with a social provider

---

app/channels/explore/template.hbs

center the channel filter form on /explore

---

app/channels/index/template.hbs

visual tweak for more dynamism on homepage

center the channel on homepage vertically on each lines, visually

---

app/channel/home/route.js
app/channel/home/template.hbs
app/channel/template.hbs
app/components/channel-header/template.hbs
app/router.js
app/styles/layout/_layout.scss
app/styles/layout/_sections.scss
tests/unit/channel/home/route-test.js

add a `/:channel/home` page for having the image and title full screen

add channel home route

---

app/channel/loading/template.hbs
app/channels/loading/template.hbs
app/styles/layout/_sections.scss
app/templates/loading.hbs

feels snapier?! and requires less eyes movement to understand what is going on.
The information centers a little in the middle while loading

improve loading ui with vertically center loaders

---

app/about/intro/template.hbs
app/auth/login/template.hbs
app/auth/signup/template.hbs
app/components/aside-navigation/template.hbs
app/components/user-login/template.hbs
app/components/user-signup/component.js
app/components/user-signup/template.hbs
app/styles/layout/_sections.scss

simplify and improve the login/signup ui flow

improve login UI

---

app/settings/account/controller.js
app/settings/account/template.hbs

As title says.
Most simple UI, just send a mail to the user.
Also it kind of ensure that a user "even more owns the account", since they can access their email account.

add password rest link in settings.account

---

app/components/channel-card/template.hbs
app/styles/components/_channel-card.scss

improve .ChannelCard to fit smaller screen, not such a big image

make channel-card work better for mobile, smaller img

---

app/channels/history/template.hbs
app/components/channels-history/template.hbs
app/services/player.js

that was actually broken, never noticed

fix listening history and active channel

---

app/auth/login/controller.js
app/auth/route.js
app/auth/signup/controller.js
app/components/user-login/component.js
app/components/user-login/template.hbs
app/styles/components/_cover.scss

fix login signup urgent?!

---

app/channel/index/template.hbs

visible only when channel has no/few track

align the channel detail body vcenter on channel.home

---

app/channels/history/template.hbs
app/components/channels-history/component.js
app/components/channels-history/template.hbs

improve clear history  btn layout, like home btns

---

app/channels/index/template.hbs
app/components/aside-channels/template.hbs

to fit in the new UI
Notable change, the button is not available on all routes anymore, but eh!

move play random channel button close to load new radios

---

app/channel/index/template.hbs
app/components/channel-sharer-url/component.js
app/styles/components/_aside.scss

simplest icon sharer to a radio

---

app/router.js
config/environment.js
package.json
yarn.lock

Closes #155 
updated the privacy doc already

Remove Google analytics

---

app/styles/components/_channel.scss

font-weight for channel external links

---

app/add/route.js

User submitted issue by mail.
I think this should fix it
Guessing a bit on the problem's origin; it is the only place in the code we're using this method `setupController`.
What do you think?

Fix adding track from url query param

---

app/components/aside-navigation/template.hbs

Remove extra "My radio" link from menu

---

app/channel/player/template.hbs

fix user flow bug unable to escape route because cannot play an empty radio

fix channel player page when no tracks in channel

---

app/components/channel-sharer-url/component.js

add title on image sharer

---

app/settings/channel/delete/template.hbs

a more direct link was possible

fix link to backup from delete radio page

---

app/components/track-form/component.js
app/utils/youtube-api.js
config/environment.js

warning api limit, update & restrict (gcould )api key, one live on stagin

---

config/environment.js

it seems we could not loggin, must have deleted credentials in google console

update projects a p i    k e y s!

---

README.md
app/utils/youtube-api.js

- use referer for youtube api key
- update doc for api keys

readme for auth & social oauth && referer for fetch youtube title

---

README.md
app/utils/youtube-api.js
config/environment.js

youtube key

---

README.md
app/about/intro/route.js
app/add/template.hbs
app/auth/signup/template.hbs
app/channel/followers/template.hbs
app/channels/explore/template.hbs
app/channels/index/template.hbs
app/components/track-edit/template.hbs
app/components/track-form-add/template.hbs
app/components/user-signup/template.hbs
app/models/track.js
app/settings/channel/delete/template.hbs
app/styles/base/_button.scss
app/styles/base/_colors.scss
app/styles/base/_config.scss
app/styles/components/_button-group.scss
app/styles/components/_map.scss
app/styles/components/_modal-dialog.scss
app/styles/layout/_container.scss
app/styles/layout/_grid.scss
config/environment.js
yarn.lock

visual tweaks and bug fixes

---

app/about/template.hbs
app/channel/template.hbs
app/channels/index/template.hbs
app/channels/template.hbs
app/components/aside-navigation/template.hbs
app/styles/app.scss
app/styles/base/_button.scss
app/styles/components/_aside.scss
app/styles/components/_button-group.scss
app/styles/components/_input-autocomplete.scss
app/styles/components/_nav.scss
app/styles/components/_playback.scss
app/styles/layout/_grid.scss
app/styles/layout/_root.scss
app/styles/layout/_sections.scss

- fixes to the bottom of the screne the navigation on / and /tracks

fix the second-level main-navigation to the bottom, adapt layout

---

app/about/intro/template.hbs

fix sign-up link

---

app/channels/index/template.hbs

fix-home text, more accessible

---

config/environment.js

test new prod server

---

config/environment.js

- cancel returning to old api values after correct user import with the pass hashes
- use new api values, radio4000-prod

(cancel: fallback to old api values) use new api values

---

app/components/x-playback/template.hbs
package.json
yarn.lock

try out `#text2speech` for new years celebrations

#text2speech will make window.voiceSymtehsis.say(track.body)

---

app/channel/template.hbs
app/components/channels-history/template.hbs

before this pull request, forced refreshed production branch to the actual state of master

fix tweaks

---

app/components/x-playback/template.hbs
app/styles/components/_aside.scss
app/styles/components/_playback.scss
app/styles/layout/_root.scss

fix player on mobile when not showing...

improve player minimize derictions in responsive

---

app/settings/channel/backup/template.hbs

rm r4 npm module form backup package

rm npm module from settings page

---

app/components/user-login/template.hbs
app/components/user-signup/template.hbs
app/settings/account/template.hbs

Remove markup for registering with social providers.

disable register with social providers, add message on settings

---

app/channel/delete/controller.js

improve delete channel flow when deleting account

transition to settings after delete channel

---

app/components/x-playback/template.hbs
package.json
yarn.lock

See https://github.com/internet4000/radio4000-player/pull/158

update r4-player api to using platform="true"

---

app/feedback/template.hbs

feedback form using google was down; remove it in favor of other methods

remove feedback form

---

app/about/contact/template.hbs

fix chat link to https://matrix.to/#/#radio4000:matrix.org

Update about/contact/chat (https://matrix.to/#/#radio4000:matrix.org)
